name: Build iverilog image
on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          push: true
          tags: verilog-cpu/builder:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
