name: Build iverilog image
on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          push: true
          registry: gchr.io
          tags: ghcr.io/jpnock/verilog-cpu/builder:v11.0.0
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
