name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/jpnock/verilog-cpu/builder:v11.1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        id: build_and_test
        timeout-minutes: 1
        run: |
          make
